- type: entities
  # title: Alarm
  entities:
    - input_boolean.alarm

- type: picture-entity
  entity: camera.front_door

- type: picture-entity
  entity: camera.side

- type: picture-entity
  entity: camera.garden

- type: picture-entity
  entity: camera.kitchen

- type: entities
  title: Motion Sensors
  show_header_toggle: false
  entities:
    - entity: binary_sensor.front_door_camera_motion
      name: Front Door Camera
    - entity: binary_sensor.porch_motion
      name: Porch Motion Sensor (Night)
    - entity: binary_sensor.dining_room_motion_sensor_occupancy
      name: Dining Room Motion Sensor
    - entity: binary_sensor.stairs_motion_sensor_occupancy
      name: Stairs Motion Sensor
    - entity: binary_sensor.kitchen_motion_sensor_occupancy
      name: Kitchen Motion Sensor
    - entity: binary_sensor.bathroom_motion_sensor_occupancy
      name: Bathroom Motion Sensor
    - entity: binary_sensor.garden_camera_motion
      name: Garden Camera
    - entity: binary_sensor.side_camera_motion
      name: Side Camera

- type: entities
  title: Doors / Windows
  show_header_toggle: false
  entities:
    - type: section
      label: External Doors
    - entity: binary_sensor.front_door_contact
      name: Front Door
    - entity: binary_sensor.garden_door_contact
      name: Garden Door
    - entity: binary_sensor.patio_doors_contact
      name: Patio Doors

    - type: section
      label: Internal Doors
    - entity: binary_sensor.kitchen_door_sensor_contact
      name: Kitchen Door
    - entity: binary_sensor.front_room_door_sensor_contact
      name: Front Room Door
    - entity: binary_sensor.bathroom_door_sensor_contact
      name: Bathroom Door
    - entity: binary_sensor.master_bedroom_door_sensor_contact
      name: Master Bedroom Door
    - entity: binary_sensor.blues_room_door_sensor_contact
      name: Blue's Bedroom Door

    - type: section
      label: Windows
    - entity: binary_sensor.bedroom_window_contact
      name: Bedroom Window
      icon: mdi:window-open-variant
