- type: entities
  title: Scenes
  show_header_toggle: false
  entities:
    - scene.downstairs_general
    - scene.front_room_dim
    - scene.downstairs_off
    - entity: group.all_lights
      name: All Lights
      icon: mdi:lighthouse

- type: entities
  title: Frontroom
  entities:
    - light.front_room_lamp
    - group.tv

- type: entities
  title: Bathroom
  entities:
    - light.bathroom_lights
    - light.bathroom_mirror_lights

- type: entities
  title: Bedroom
  show_header_toggle: false
  entities:
    - light.master_bedroom_main
    - light.bedroom_lamps
    - entity: cover.master_bedroom
      name: Blind
      secondary_info: position
    - script.master_bedroom_blind_fan
    - entity: switch.fan
      name: Fan
      icon: mdi:fan

- type: entities
  title: Kitchen
  entities:
    - light.main_kitchen_lights
    - group.kitchen_low

- type: entities
  title: Stairs
  show_header_toggle: false
  entities:
    - light.stairs
    - input_select.stairs_mode

- type: entities
  title: Landing
  show_header_toggle: false
  entities:
    - light.landing_light

- type: entities
  title: Dining Room
  entities:
    - entity: switch.coat_rack
      name: Coat Rack
      icon: mdi:hanger
    - entity: light.entrance_light
      name: Entrance Light
    - light.dining_room_lamp

- type: entities
  title: Outdoors
  # show_header_toggle: false
  entities:
    - light.garden_lights
    - entity: light.porch_light
      name: Porch Light
      icon: mdi:coach-lamp

- type: shopping-list
  title: Shopping List
