- type: entities
  title: Scenes
  show_header_toggle: false
  entities:
    - scene.downstairs_general
    - scene.downstairs_timeout
    - scene.downstairs_dim
    - scene.downstairs_off
    - entity: group.all_lights
      name: All Lights
      icon: mdi:lighthouse

- type: entities
  title: Frontroom
  entities:
    - light.front_room_lamp
    - group.tv
    - entity: light.corner_lamp
      name: Corner Lamp
      icon: mdi:led-strip-variant
    - input_select.maestro_corner_lamp
    - entity: group.ambilight
      icon: mdi:television-ambient-light

- type: entities
  title: Bathroom
  entities:
    - light.bathroom_all
    - light.bathroom_mirror_lights

- type: entities
  title: Bedroom
  show_header_toggle: false
  entities:
    - light.master_bedroom_main
    - light.bedroom_lamps
    - entity: cover.bedroom_blind
      name: Blind
      secondary_info: position
    - script.master_bedroom_blind_fan
    - entity: sensor.bedroom_blind_battery
      name: Blind Battery

- type: entities
  title: Kitchen
  entities:
    - light.main_kitchen_lights
    - entity: group.kitchen_leds
      icon: mdi:led-strip-variant

- type: entities
  title: Stairs
  show_header_toggle: false
  entities:
    - light.stairs
    - input_select.maestro_stairs

- type: entities
  title: Landing
  show_header_toggle: false
  entities:
    - light.landing_light

- type: entities
  title: Office
  entities:
    - entity: switch.ikea_socket_switch
      name: Office Lamp
      icon: mdi:lightbulb

- type: entities
  title: Dining Room
  entities:
    - entity: light.entrance_light
      name: Entrance Light
    - light.dining_room_lamp
    - entity: switch.coat_rack
      name: Coat Rack
      icon: mdi:hanger

- type: entities
  title: Outdoors
  entities:
    - light.garden_lights
    - entity: light.porch_light
      name: Porch Light
      icon: mdi:coach-lamp

- type: shopping-list
  title: Shopping List
