- platform: mqtt
  name: Clothes Dryer
  command_topic: "switch/dryer"
  state_topic: "switch/dryer/state"
  #availability_topic: "switch/dryer/availability"
  payload_available: "1"
  payload_not_available: "0"
  payload_on: "1"
  payload_off: "0"

# Switch to enable/disable zigbee2mqtt pairing.
- platform: mqtt
  name: zigbee_pairing
  command_topic: zigbee/bridge/config/permit_join
  state_topic: zigbee/bridge/config
  payload_on: true
  payload_off: false
  value_template: "{{ value_json.permit_join }}"

- platform: mqtt
  name: coat_rack
  command_topic: 2NICE-1/cmnd/POWER
  state_topic: 2NICE-1/stat/POWER
  payload_on: "ON"
  payload_off: "OFF"

- platform: mqtt
  name: microwave
  command_topic: 2NICE-3/cmnd/POWER
  state_topic: 2NICE-3/stat/POWER
  payload_on: "ON"
  payload_off: "OFF"
