- platform: mqtt
  name: Stairs
  state_topic: "light/stairs/state"
  command_topic: "light/stairs"
  rgb_state_topic: "light/stairs/rgb/state"
  rgb_command_topic: "light/stairs/rgb"
  availability_topic: "light/stairs/availability"
  payload_not_available: "0"
  payload_available: "1"
  payload_off: "0"
  payload_on: "1"
  retain: false

- platform: mqtt
  name: Landing Light
  state_topic: "light/landing/state"
  command_topic: "light/landing"
  payload_off: "0"
  payload_on: "1"
  retain: false

- platform: mqtt
  name: Bathroom Lights
  state_topic: "light/bathroom/state"
  command_topic: "light/bathroom"
  payload_off: "0"
  payload_on: "1"
  retain: false

- platform: mqtt
  name: Bathroom Mirror Lights
  command_topic: "shellies/shelly1-2272F1/relay/0/command"
  state_topic: "shellies/shelly1-2272F1/relay/0"
  payload_off: "off"
  payload_on: "on"
  retain: false

- platform: mqtt
  name: Main Kitchen Lights
  state_topic: "light/kitchen/state"
  command_topic: "light/kitchen"
  payload_off: "0"
  payload_on: "1"
  retain: false

- platform: mqtt
  name: Dining Room Lamp
  state_topic: "light/dining_room_lamp/state"
  command_topic: "light/dining_room_lamp"
  payload_off: "0"
  payload_on: "1"
  retain: false

- platform: mqtt
  name: Front Room Lamp
  state_topic: "light/front_room_lamp/state"
  command_topic: "light/front_room_lamp"
  payload_off: "0"
  payload_on: "1"
  retain: false

- platform: mqtt
  name: Master Bedroom Main
  command_topic: "light/master_bedroom_main"
  state_topic: "light/master_bedroom_main/state"
  payload_on: "1"
  payload_off: "0"
  retain: false

- platform: mqtt
  name: Garden Lights
  command_topic: "shellies/shelly1-32CDCA/relay/0/command"
  state_topic: "shellies/shelly1-32CDCA/relay/0"
  payload_on: "on"
  payload_off: "off"
  retain: false

- platform: mqtt
  name: porch_light
  command_topic: "shellies/shelly1-227D0A/relay/0/command"
  state_topic: "shellies/shelly1-227D0A/relay/0"
  payload_on: "on"
  payload_off: "off"
  retain: false

- platform: mqtt
  name: entrance_light
  command_topic: "shellies/shelly1-76F1B6/relay/0/command"
  state_topic: "shellies/shelly1-76F1B6/relay/0"
  payload_on: "on"
  payload_off: "off"
  retain: false
