# Change the HDMI switcher to the Chromecast input when the Chromecast starts being used.
- alias: auto_chromecast_input_on
  initial_state: true
  trigger:
    platform: state
    entity_id: media_player.chromecast3116
    to: "idle"
  action:
    service: script.input_chromecast

# Change the HDMI switcher to the Sky Box input when the Chromecast stops being used.
- alias: auto_chromecast_input_off
  initial_state: true
  trigger:
    platform: state
    entity_id: media_player.chromecast3116
    to: "off"
  action:
    service: script.input_sky
