# Toggle the bedroom lamps when the bedroom Xiaomi switch is pressed once.
- alias: master_bedroom_xiaomi_switch_single_click
  initial_state: true
  trigger:
    platform: state
    entity_id: sensor.master_bedroom_xiaomi_switch_click
    to: "single"
  action:
    - service: light.toggle
      entity_id: light.bedroom_lamps

# Set a warm colour when the bedroom Xiaomi switch is pressed twice.
- alias: master_bedroom_xiaomi_switch_double_click
  initial_state: true
  trigger:
    platform: state
    entity_id: sensor.master_bedroom_xiaomi_switch_click
    to: "double"
  action:
    service: light.turn_on
    data:
      entity_id: light.bedroom_lamps
      xy_color: [0.50, 0.42]

# Toggle the main bedroom lights when the bedroom Xiaomi switch is quadruple pressed
- alias: master_bedroom_xiaomi_switch_quadruple_click
  initial_state: true
  trigger:
    platform: state
    entity_id: sensor.master_bedroom_xiaomi_switch_click
    to: "quadruple"
  action:
    service: light.toggle
    data:
      entity_id: light.master_bedroom_main

# Set a darker warm colour when the bedroom Xiaomi switch is long pressed.
- alias: master_bedroom_xiaomi_switch_long_press
  initial_state: true
  trigger:
    platform: state
    entity_id: sensor.master_bedroom_xiaomi_switch_click
    to: "long"
  action:
    service: light.turn_on
    data:
      entity_id: light.bedroom_lamps
      xy_color: [0.638, 0.288]
