# Turn the volumes down on the google homes at night.
- alias: google_home_volumes_night
  initial_state: true
  trigger:
    platform: time
    at: "19:30:00"
  action:
    # Dining Room
    - service: media_player.volume_set
      data:
        entity_id: media_player.google_home_dining_room
        volume_level: 0.3
    # Front Room
    - service: media_player.volume_set
      data:
        entity_id: media_player.google_home_front_room
        volume_level: 0.4
    # Kitchen
    - service: media_player.volume_set
      data:
        entity_id: media_player.kitchen_display
        volume_level: 0.6
    # Bathroom
    - service: media_player.volume_set
      data:
        entity_id: media_player.nest_mini_bathroom
        volume_level: 0.2

# Turn the volumes up on the google homes in the morning.
- alias: google_home_volumes_day
  initial_state: true
  trigger:
    platform: time
    at: "08:00:00"
  action:
    # Dining Room
    - service: media_player.volume_set
      data:
        entity_id: media_player.google_home_dining_room
        volume_level: 0.6
    # Front Room
    - service: media_player.volume_set
      data:
        entity_id: media_player.google_home_front_room
        volume_level: 0.4
    # Kitchen
    - service: media_player.volume_set
      data:
        entity_id: media_player.kitchen_display
        volume_level: 0.7
    # Bathroom
    - service: media_player.volume_set
      data:
        entity_id: media_player.nest_mini_bathroom
        volume_level: 0.4
