- alias: lodge_auto_heat_on
  initial_state: true
  trigger:
    platform: state
    entity_id: input_boolean.lodge_auto_heat
    to: 'on'
  action:
    - service: script.lodge_auto_heat

- alias: lodge_auto_heat_off
  initial_state: true
  trigger:
    platform: state
    entity_id: input_boolean.lodge_auto_heat
    to: 'off'
  action:
    - service: climate.turn_off
      target:
        entity_id: climate.lodge_ac

- alias: lodge_auto_heat_temp_change
  initial_state: true
  trigger:
    platform: state
    entity_id: sensor.lodge_ac_temperature
  condition:
    condition: state
    entity_id: input_boolean.lodge_auto_heat
    state: 'on'
  action:
    - service: script.lodge_auto_heat

- alias: lodge_auto_heat_ac_off
  initial_state: true
  trigger:
    platform: state
    entity_id: climate.lodge_ac
    to: 'off'
  action: 
    service: input_boolean.turn_off
    entity_id: input_boolean.lodge_auto_heat
