# Turn the microwave off and then on again at 1am. When reset, the default time for the microwave is 1am so this syncronises the clock :-).
- alias: microwave_clock_reset
  initial_state: true
  trigger:
    platform: time
    at: "00:59:50"
  action:
    - service: switch.turn_off
      entity_id: switch.microwave
    - delay:
        seconds: 10
    - service: switch.turn_on
      entity_id: switch.microwave
