# Test automation.
- alias: xiaomi_wall_switch_single_click
  initial_state: true
  trigger:
    platform: state
    entity_id: sensor.0x00158d000355a3ff_click
    to: single
  action:
    service: notify.mobile_app_dullage_s_iphone
    data:
      message: "Single Click"
