scene.downstairs_general:
  name: Downstairs General
scene.downstairs_dim:
  name: Front Room Dim
light.front_room_lamp:
  name: Front Room Lamp
script.going_out:
  name: Going Out Script
light.main_kitchen_lights:
  name: Kitchen Lights
light.garden_all:
  name: Garden Lights
light.landing:
  name: Landing Light
light.bathroom_all:
  name: Bathroom Lights
light.master_bedroom_all:
  name: Bedroom Lights
light.bedroom_lamps:
  name: Bedroom Lamps
media_player.apple_tv:
  name: TV
light.porch_light:
  name: Porch Light
light.entrance_light:
  name: Entrance Light
light.corner_lamp:
  name: Corner Lamp
script.goodnight:
  name: Goodnight Script
cover.master_bedroom:
  name: Bedroom Blind
climate.wiser_home:
  name: House Heating
climate.lodge_ac:
  name: Lodge AC
input_boolean.video_call_lights:
  name: Video Call Lights
camera.front_door:
  name: Front Door Camera
  linked_doorbell_sensor: binary_sensor.doorbell_automation_running
scene.lodge_general:
  name: Lodge General
scene.lodge_video_call:
  name: Lodge Video Call
