# Ad-hoc Heating
ad_hoc_heating_time_hour:
  name: Hour
  icon: mdi:timer
  initial: 0
  min: 0
  max: 23
  step: 1

ad_hoc_heating_time_minute:
  name: Minutes
  icon: mdi:timer
  initial: 0
  min: 0
  max: 55
  step: 5

# Dryer Timeout
dryer_timeout:
  name: Dryer Timeout
  icon: mdi:progress-clock
  step: 1
  min: 0
  max: 999
  mode: box
  unit_of_measurement: mins

heater_target:
  name: Heater Target
  icon: mdi:temperature-celsius
  initial: 21
  min: 18
  max: 24
  step: 0.5
  unit_of_measurement: "Â°C"
